spring.application.name=event-registration
server.port=9000

# MongoDB
spring.mongodb.uri=mongodb://localhost:27017/event_management
spring.data.mongodb.auto-index-creation=true

#logging.level.root=DEBUG

# Kafka broker
spring.kafka.bootstrap=localhost:9002

# Consumer group - individual consumers can override this config
spring.kafka.consumer.group-id=event-registration

# Serialize Kafka message key
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

# Serialize Kafka message value
spring.kafka.producer.value-serializer=